server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE:jdbc:postgresql://localhost:5433/muscletracking?currentSchema=test}
    username: mtadmin
    password: mtadmin

doma:
  dialect: POSTGRES